name: macOS

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: "-D warnings"

jobs:
  stats:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7
      - name: Test Stats on macOS
        run: "cargo test -j 2 tools::stats::"
